remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Property prospect lists for Florida counties  .]
description: [Properties in distress with high propects of becoming available for sale.]